# Generated by Django 6.0.1 on 2026-02-01 09:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exerciselog',
            unique_together={('user', 'date')},
        ),
    ]
